### ISSUE TITLE
CORE: add author name & email to be shown with the notes in the search function.

### ISSUE THREAD

**Issue by mitrinh** [Game-Of-Threads/CS4800Project#14]
Currently, the search only returns the note information from the course name. We want to see who wrote the saved notes from the search bar and their email preferably. BE SURE TO USE THE CORRECT VARIABLE NAMES THAT MATCH WITH THE ONES IN APP.JS AND THE OTHER FILES.

**Comment by DrewU** [comment]
Added name to search results, email is something that shouldn't be displayed.
